name: Deploy to Dev

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6.0.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: 'package.json' # read node version from engines defined in package.json

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --configuration=production

      - name: Create Build Archive
        run: |
          cd dist/line-item-app/browser
          zip -rq ../../../${GITHUB_SHA}.zip .

      - name: Upload Build Archive to S3
        run: |
          aws s3 cp \
            ${GITHUB_SHA}.zip \
            s3://${{ vars.AWS_ARTIFACT_BUCKET_NAME }}/${GITHUB_SHA}.zip

      - name: Run Shared Deployment Steps
        uses: ./.github/actions/deploy-app-steps
        with:
          build-folder: './dist/line-item-app/browser'
          target-bucket-name: ${{ vars.AWS_S3_BUCKET_NAME }}
          cloudfront-distribution-id: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
