name: Promote/Rollback

on:
  workflow_dispatch:
    inputs:
      target-environment:
        description: 'Target environment'
        required: true
        type: choice
        options:
          - dev
          - uat
          - prod
      build-version:
        description: 'Build version to deploy'
        type: string
        required: true

jobs:
  promote-or-rollback:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target-environment }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Download Build Archive
        run: |
          aws s3 cp s3://${{ vars.AWS_ARTIFACT_BUCKET_NAME }}/${{ inputs.build-version }}.zip .

      - name: Unzip Build Archive
        run: |
          unzip ./${{ inputs.build-version }}.zip -d ./extracted

      - name: Run Shared Deployment Steps
        uses: ./.github/actions/deploy-app-steps
        with:
          build-folder: './extracted'
          target-bucket-name: ${{ vars.AWS_S3_BUCKET_NAME }}
          cloudfront-distribution-id: ${{ vars.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
